-- ~/.config/nvim/lua/plugins/which-key.lua
-- Explicit cheat sheet — press <leader>? to see all keymaps

return {
    "folke/which-key.nvim",
    event = "VeryLazy",
    keys = {
        { "<leader>k", function() require("which-key").show({ keys = "<leader>" }) end, desc = "Cheat sheet (keymaps)" },
    },
    opts = {
        preset = "modern",
        spec = {
            { "<leader>f",  group = "Find" },
            { "<leader>ff", desc = "Find files" },
            { "<leader>fg", desc = "Live grep" },
            { "<leader>fb", desc = "Buffers" },
            { "<leader>fp", desc = "Projects" },
            { "<leader>x",  group = "Diagnostics" },
            { "<leader>xx", desc = "Toggle diagnostics" },
            { "<leader>xX", desc = "Buffer diagnostics" },
            { "<leader>g",  group = "Git" },
            { "<leader>gg", desc = "Status (Neogit)" },
            { "<leader>h",  group = "Hunk" },
            { "<leader>hs", desc = "Stage hunk" },
            { "<leader>hr", desc = "Reset hunk" },
            { "<leader>hp", desc = "Preview hunk" },
            { "<leader>hb", desc = "Blame line" },
            { "<leader>r",  group = "Refactor" },
            { "<leader>rn", desc = "Rename" },
            { "<leader>c",  group = "Code" },
            { "<leader>ca", desc = "Code action" },
            { "<leader>s",  group = "Search" },
            { "<leader>sj", desc = "Jump to position" },
            { "<leader>st", desc = "Jump treesitter node" },
            { "<leader>e",  desc = "Toggle file tree" },
            { "<leader>k",  desc = "Cheat sheet" },
            { "gc",  group = "Comment" },
            { "gb",  group = "Block comment" },
            { "[d",  desc = "Prev diagnostic" },
            { "]d",  desc = "Next diagnostic" },
            { "[c",  desc = "Prev hunk" },
            { "]c",  desc = "Next hunk" },
        },
    },
}
